import Foundation
import Autostart

/// Die zwei systemd-Nutzer-Units des Auto-Updates — Namen, Marker, Text und
/// die Auswertung ihrer `systemctl`-Antworten (CM-29). Reines Rendern, kein
/// Dateizugriff.
///
/// Die Units werden nur beim Einrichten geschrieben. Ein Update schreibt
/// keine Unit neu: Ihr Text bleibt auf dem Stand der Einrichtung (FE 17).
public enum UpdateUnits {

    /// Der Timer — er allein wird eingeschaltet.
    public static let timerName = "claude-monitor-tray-update.timer"
    /// Der Service, den der Timer auslöst. **Statisch** (ohne `[Install]`).
    public static let serviceName = "claude-monitor-tray-update.service"
    /// Die Zielgruppe des Timers.
    public static let timerInstallTarget = "timers.target"

    /// Die Zeile, an der die Einrichtung ihre eigenen Dateien wiedererkennt —
    /// eine andere als die der Autostart-Unit.
    public static let markerComment = "# generated by claude-monitor-tray --install-auto-update"

    /// Obergrenze eines Service-Laufs.
    ///
    /// `Type=oneshot` hat ohne `TimeoutStartSec=` keine Startgrenze. Hinge
    /// ein Abruf oder die Ladeprobe, bliebe der Dienst „activating", und der
    /// Timer stieße ihn nie wieder an. Der Wert liegt über der Summe der
    /// Einzelgrenzen (Manifest 120 s, Tarball 600 s, Ladeprobe 30 s).
    public static let serviceStartTimeout = "30min"

    /// Erste Prüfung nach dem Start des Nutzermanagers.
    public static let firstCheckDelay = "15min"
    /// Abstand der Prüfungen, gemessen ab der letzten Aktivierung.
    public static let checkInterval = "1d"

    /// Der Timer.
    ///
    /// **Kein** `Persistent=`: Damit legte systemd eine Zeitstempeldatei an
    /// (`man systemd.timer`) — „nothing is left behind" hielte nicht mehr.
    public static func renderTimer() -> String {
        """
        \(markerComment)
        [Unit]
        Description=ClaudeMonitor tray: daily update check

        [Timer]
        OnStartupSec=\(firstCheckDelay)
        OnUnitActiveSec=\(checkInterval)

        [Install]
        WantedBy=\(timerInstallTarget)

        """
    }

    /// Der Service — ruft das Binary mit `--update` auf.
    ///
    /// `ExecStart=` über ``AutostartUnit/execStartValue(for:)``: die EINE
    /// Quoting-Regel (Folge sonst `203/EXEC`).
    public static func renderService(executablePath: String) -> String {
        """
        \(markerComment)
        [Unit]
        Description=ClaudeMonitor tray: install an available update

        [Service]
        Type=oneshot
        ExecStart=\(AutostartUnit.execStartValue(for: executablePath)) --update
        TimeoutStartSec=\(serviceStartTimeout)

        """
    }

    // MARK: - Zustands-Lesart des statischen Service (2b-Auflage 1)

    /// Was `systemctl --user is-enabled` über den **statischen** Service sagt.
    ///
    /// Eine Unit ohne `[Install]` antwortet mit `static`. Über
    /// ``AutostartStatus/reading(isEnabledOutput:exitStatus:standardError:didRun:)``
    /// wäre das ein unerwartetes Wort — jedes zweite Einrichten und jedes
    /// Entfernen endete mit 11.
    public enum ServiceReading: Equatable, Sendable {
        /// Eine Datei liegt vor und ist nicht maskiert (`static`; `disabled`/
        /// `enabled` heißt: eine Datei MIT `[Install]` — nicht die eigene, das
        /// entscheidet die Marker-Prüfung).
        case present
        /// Maskiert.
        case masked
        /// Keine Datei (`not-found`).
        case absent
        /// Ein bekanntes Wort ohne Bedeutung hier.
        case unexpected(word: String)
        /// Kein bekanntes Wort.
        case unreadable(word: String)
        /// Kein Nutzermanager erreichbar.
        case managerUnavailable
        /// `systemctl` wurde gar nicht erst gestartet.
        case didNotRun(reason: String)
    }

    /// Wertet `is-enabled` für den Service aus.
    public static func serviceReading(
        isEnabledOutput: String,
        exitStatus: Int32,
        standardError: String,
        didRun: Bool = true
    ) -> ServiceReading {
        guard didRun else { return .didNotRun(reason: standardError) }
        let word = AutostartStatus.firstWordOfOutput(isEnabledOutput)
        if AutostartStatus.isManagerUnavailable(word: word, exitStatus: exitStatus, standardError: standardError) {
            return .managerUnavailable
        }
        switch word {
        case "static", "disabled", "enabled", "enabled-runtime":
            return .present
        case "masked", "masked-runtime":
            return .masked
        case "not-found":
            return .absent
        case "linked", "linked-runtime", "alias", "indirect", "generated", "transient", "bad":
            return .unexpected(word: word)
        default:
            return .unreadable(word: word)
        }
    }

    // MARK: - Letzter Lauf (2b-Auflage 9)

    /// Ein Lauf des Service, der mit 12 oder 13 endete.
    public struct FailedRun: Equatable, Sendable {
        /// 12 oder 13.
        public let exitStatus: Int
        /// `ExecMainExitTimestamp`, roh; leer, wenn systemd keinen nennt.
        public let timestamp: String

        public init(exitStatus: Int, timestamp: String) {
            self.exitStatus = exitStatus
            self.timestamp = timestamp
        }
    }

    /// Liest `systemctl --user show -p Result,ExecMainStatus,ExecMainExitTimestamp`.
    ///
    /// Nur 12 und 13 ergeben einen Eintrag: das sind die Codes, mit denen ein
    /// Update-Lauf „nichts gemessen" bzw. „abgelehnt" meldet. Ohne diese
    /// Zeile meldete der Status „enabled", während jeder Lauf scheitert.
    public static func failedRun(fromShowOutput output: String) -> FailedRun? {
        var values: [String: String] = [:]
        for line in output.split(separator: "\n") {
            guard let equals = line.firstIndex(of: "=") else { continue }
            values[String(line[..<equals])] = String(line[line.index(after: equals)...])
        }
        guard let raw = values["ExecMainStatus"], let status = Int(raw), status == 12 || status == 13 else {
            return nil
        }
        return FailedRun(exitStatus: status, timestamp: values["ExecMainExitTimestamp"] ?? "")
    }
}
