import Foundation

/// Der Text der systemd-Nutzer-Unit — reines Rendern, kein Dateizugriff.
public enum AutostartUnit {

    /// Die Zeile, an der die Einrichtung ihre **eigene** Datei wiedererkennt.
    ///
    /// Ohne sie ließe sich eine von Hand geschriebene Unit gleichen Namens
    /// nicht von der erzeugten unterscheiden — und `--install-autostart`
    /// überschriebe fremde Arbeit.
    public static let markerComment = "# generated by claude-monitor-tray --install-autostart"

    /// Beendigungscodes, nach denen ein Neustart nichts besser macht.
    ///
    /// * `5` — keine Sitzung (`DBUS_SESSION_BUS_ADDRESS` fehlt).
    /// * `8` — es läuft bereits eine Instanz.
    /// * `127` — der dynamische Lader fand eine Bibliothek nicht. Kein Code der
    ///   App und keiner von systemd; trifft nur Builds ohne
    ///   `--static-swift-stdlib`, deren RUNPATH in eine entfernte oder
    ///   gewechselte Toolchain zeigt. Ein Neustart findet dieselbe Lücke.
    /// * `203` — systemd konnte das Binary nicht ausführen (`203/EXEC`:
    ///   gelöscht, verschoben, nicht ausführbar). Das ist kein Code der App,
    ///   sondern ein Code von systemd; ein Neustart findet dieselbe Datei nicht
    ///   wieder.
    ///
    /// **`7` und `9` stehen bewusst NICHT hier**: Beide kann nur `--selftest`
    /// erzeugen, und der Dienst startet das Binary ohne diesen Schalter — ein
    /// Ausschluss für einen Code, der im Dienst nie vorkommt, wäre toter Text.
    /// `7` = Abfragefolge blieb aus, Auflage 15a. `9` = kein
    /// `org.kde.StatusNotifierWatcher` auf dem Bus (CM-33); ohne Watcher wartet
    /// der Prozess im Normalbetrieb, statt zu enden.
    ///
    /// **`6` steht ebenfalls bewusst NICHT hier**: Ein Busabriss ist der eine
    /// Fehler, der von selbst vergeht (GNOME-Shell-Neustart, kurzer
    /// Bus-Hänger). Genau dort ist ein Neustart sinnvoll, und genau dafür ist
    /// `Restart=on-failure` da.
    public static let restartPreventExitStatus = "5 8 127 203"

    /// Rendert die Unit für einen **absoluten** Binärpfad.
    ///
    /// Keine `Environment=`-Zeile: `DBUS_SESSION_BUS_ADDRESS`, `HOME` und
    /// `XDG_RUNTIME_DIR` führt der Nutzermanager bereits selbst (gemessen über
    /// `systemctl --user show-environment`). Eine eigene Kopie hier wäre ein
    /// zweiter Wahrheitsort, der beim nächsten Sitzungswechsel veraltet.
    public static func render(executablePath: String) -> String {
        """
        \(markerComment)
        [Unit]
        Description=ClaudeMonitor tray icon
        After=\(AutostartPaths.installTargetName)
        PartOf=\(AutostartPaths.installTargetName)

        [Service]
        Type=simple
        ExecStart=\(execStartValue(for: executablePath))
        Restart=on-failure
        RestartSec=5
        RestartPreventExitStatus=\(restartPreventExitStatus)

        [Install]
        WantedBy=\(AutostartPaths.installTargetName)

        """
    }

    /// Ob ein vorgefundener Dateiinhalt von dieser Einrichtung stammt.
    public static func carriesMarker(_ contents: String) -> Bool {
        carriesMarker(contents, marker: markerComment)
    }

    /// Ob ein vorgefundener Dateiinhalt eine bestimmte Marker-Zeile trägt.
    ///
    /// CM-29: Jede Unit dieses Programms hat ihren EIGENEN Marker (Autostart,
    /// Update-Timer, Update-Service) — die Prüfung ist dieselbe, nur die Zeile
    /// kommt vom Aufrufer.
    public static func carriesMarker(_ contents: String, marker: String) -> Bool {
        contents.split(separator: "\n", omittingEmptySubsequences: false).contains { line in
            line.trimmingCharacters(in: .whitespaces) == marker
        }
    }

    /// Der Wert hinter `ExecStart=`.
    ///
    /// systemd zerlegt die Zeile in Wörter; ein Leerzeichen im Pfad machte aus
    /// dem Rest Argumente und der Dienst scheiterte mit `203/EXEC`. Deshalb
    /// wird bei Leerzeichen, Anführungszeichen oder Rückstrich gequotet.
    ///
    /// CM-38: Jedes `%` wird als `%%` geschrieben, gequotet wie ungequotet —
    /// systemd expandiert Spezifier in der Befehlszeile. Ein unmaskiertes `%`
    /// hat zwei Folgen: `%h` & Co. ergeben einen falschen Pfad, ein `%` mit
    /// unbekanntem Buchstaben (`%Z`) lässt die Unit gar nicht laden. `$` bleibt
    /// unmaskiert: im Programmwort ersetzt systemd es weder beim Laden noch
    /// beim Start (gemessen, `$$` würde den Pfad sogar verfälschen).
    ///
    /// Die Zeichenebene ist durchgehend `unicodeScalars`, nicht `Character`:
    /// Swift fasst `%`, ` `, `"` und `\` mit einem folgenden Kombinationszeichen
    /// zu einem Character zusammen, systemd liest Bytes.
    ///
    /// Pfade mit `'`, `"`, `\` oder Steuerzeichen nimmt systemd in `ExecStart=`
    /// nicht an (``pathRefusedBySystemd(_:)``); die Einrichtung verweigert sie.
    ///
    /// CM-29: Die Regel `needsQuoting` steht NUR hier; auch die Service-Unit
    /// des Auto-Updates (`UpdateUnits`) rendert ihr `ExecStart=` hierüber.
    public static func execStartValue(for executablePath: String) -> String {
        var escaped = String.UnicodeScalarView()
        var needsQuoting = false
        for scalar in executablePath.unicodeScalars {
            if quotingTriggers.contains(scalar) { needsQuoting = true }
            if scalar == "%" || scalar == "\"" || scalar == "\\" {
                escaped.append(scalar == "%" ? "%" : "\\")
            }
            escaped.append(scalar)
        }
        let value = String(escaped)
        return needsQuoting ? "\"\(value)\"" : value
    }

    /// Ob systemd den Pfad als Programmpfad in `ExecStart=` ablehnt (CM-38).
    ///
    /// Gemessen (systemd 259): `"`, `'`, `\`, U+0001–U+001F und U+007F ergeben
    /// „Executable path contains special characters“, die Unit lädt nicht.
    public static func pathRefusedBySystemd(_ path: String) -> Bool {
        path.unicodeScalars.contains { scalar in
            scalar == "\"" || scalar == "'" || scalar == "\\"
                || (1...0x1F).contains(scalar.value) || scalar.value == 0x7F
        }
    }

    /// Der Programmpfad aus einer Unit — Gegenstück zu ``execStartValue(for:)`` (CM-34).
    ///
    /// Nimmt nur die zwei Formen an, die ``execStartValue(for:)`` erzeugt:
    /// ungequotet = ein Wort ohne `"`, `'` und `\`; gequotet = beginnt mit `"`,
    /// einzige Escapes `\"` und `\\`, nach dem schließenden `"` folgt Leerraum
    /// oder Zeilenende. Jede andere Form liest systemd womöglich anders
    /// (Anführungszeichen mitten im Wort, C-Escapes) — dann gibt es `nil`
    /// statt einer Behauptung ohne Messung.
    ///
    /// CM-38: `%%` ergibt `%`, ein einzelnes `%` ergibt `nil` (systemd liest
    /// es als Spezifier). Enthält der dekodierte Pfad ein Zeichen, das systemd
    /// ablehnt (``pathRefusedBySystemd(_:)``), ebenfalls `nil`.
    ///
    /// Der Roundtrip `executablePath(inUnit: render(p)) == p` gilt nur für
    /// Pfade, die systemd annimmt — und nicht für Pfade, die auf Unicode-
    /// Leerraum (U+00A0) enden: die Zeilen-Trimmung (`.whitespaces`) kürzt sie
    /// (Altbestand CM-34).
    ///
    /// Text nach dem Pfad (Argumente) wird ignoriert.
    public static func executablePath(inUnit contents: String) -> String? {
        let prefix = "ExecStart="
        guard let line = contents.split(separator: "\n", omittingEmptySubsequences: false)
            .map({ $0.trimmingCharacters(in: .whitespaces) })
            .first(where: { $0.hasPrefix(prefix) }) else { return nil }
        let value = Array(line.unicodeScalars.dropFirst(prefix.unicodeScalars.count)
            .drop(while: { $0 == " " || $0 == "\t" }))
        var path = String.UnicodeScalarView()
        if value.first == "\"" {
            var index = 1
            var closed = false
            while index < value.count {
                let scalar = value[index]
                if scalar == "\\" {
                    guard index + 1 < value.count, value[index + 1] == "\"" || value[index + 1] == "\\" else {
                        return nil
                    }
                    path.append(value[index + 1])
                    index += 2
                } else if scalar == "\"" {
                    closed = true
                    index += 1
                    break
                } else {
                    path.append(scalar)
                    index += 1
                }
            }
            guard closed else { return nil }
            if index < value.count, value[index] != " ", value[index] != "\t" { return nil }
        } else {
            for scalar in value {
                if scalar == " " || scalar == "\t" { break }
                if scalar == "\"" || scalar == "'" || scalar == "\\" { return nil }
                path.append(scalar)
            }
        }
        guard let decoded = decodeSpecifierEscapes(path) else { return nil }
        guard decoded.hasPrefix("/"), !pathRefusedBySystemd(decoded) else { return nil }
        return decoded
    }

    /// `%%` ⇒ `%`; ein einzelnes `%` ⇒ `nil` (CM-38).
    private static func decodeSpecifierEscapes(_ raw: String.UnicodeScalarView) -> String? {
        var decoded = String.UnicodeScalarView()
        var iterator = raw.makeIterator()
        while let scalar = iterator.next() {
            if scalar == "%" {
                guard iterator.next() == "%" else { return nil }
            }
            decoded.append(scalar)
        }
        return String(decoded)
    }

    /// Zeichen, bei denen der Pfad gequotet wird.
    private static let quotingTriggers: Set<Unicode.Scalar> = [" ", "\"", "\\", "'"]
}
