import Foundation

/// Der Text der systemd-Nutzer-Unit — reines Rendern, kein Dateizugriff.
public enum AutostartUnit {

    /// Die Zeile, an der die Einrichtung ihre **eigene** Datei wiedererkennt.
    ///
    /// Ohne sie ließe sich eine von Hand geschriebene Unit gleichen Namens
    /// nicht von der erzeugten unterscheiden — und `--install-autostart`
    /// überschriebe fremde Arbeit.
    public static let markerComment = "# generated by claude-monitor-tray --install-autostart"

    /// Beendigungscodes, nach denen ein Neustart nichts besser macht.
    ///
    /// * `5` — keine Sitzung (`DBUS_SESSION_BUS_ADDRESS` fehlt).
    /// * `8` — es läuft bereits eine Instanz.
    /// * `9` — kein `org.kde.StatusNotifierWatcher` auf dem Bus.
    ///
    /// **`7` steht bewusst NICHT hier** (Auflage 15a): Exit 7 kann nur
    /// `--selftest` erzeugen, und der Dienst startet das Binary ohne diesen
    /// Schalter — ein Ausschluss für einen Code, der im Dienst nie vorkommt,
    /// wäre toter Text.
    ///
    /// **`6` steht ebenfalls bewusst NICHT hier**: Ein Busabriss ist der eine
    /// Fehler, der von selbst vergeht (GNOME-Shell-Neustart, kurzer
    /// Bus-Hänger). Genau dort ist ein Neustart sinnvoll, und genau dafür ist
    /// `Restart=on-failure` da.
    public static let restartPreventExitStatus = "5 8 9"

    /// Rendert die Unit für einen **absoluten** Binärpfad.
    ///
    /// Keine `Environment=`-Zeile: `DBUS_SESSION_BUS_ADDRESS`, `HOME` und
    /// `XDG_RUNTIME_DIR` führt der Nutzermanager bereits selbst (gemessen über
    /// `systemctl --user show-environment`). Eine eigene Kopie hier wäre ein
    /// zweiter Wahrheitsort, der beim nächsten Sitzungswechsel veraltet.
    public static func render(executablePath: String) -> String {
        """
        \(markerComment)
        [Unit]
        Description=ClaudeMonitor tray icon
        After=\(AutostartPaths.installTargetName)
        PartOf=\(AutostartPaths.installTargetName)

        [Service]
        Type=simple
        ExecStart=\(execStartValue(for: executablePath))
        Restart=on-failure
        RestartSec=5
        RestartPreventExitStatus=\(restartPreventExitStatus)

        [Install]
        WantedBy=\(AutostartPaths.installTargetName)

        """
    }

    /// Ob ein vorgefundener Dateiinhalt von dieser Einrichtung stammt.
    public static func carriesMarker(_ contents: String) -> Bool {
        contents.split(separator: "\n", omittingEmptySubsequences: false).contains { line in
            line.trimmingCharacters(in: .whitespaces) == markerComment
        }
    }

    /// Der Wert hinter `ExecStart=`.
    ///
    /// systemd zerlegt die Zeile in Wörter; ein Leerzeichen im Pfad machte aus
    /// dem Rest Argumente und der Dienst scheiterte mit `203/EXEC`. Deshalb
    /// wird bei Leerzeichen, Anführungszeichen oder Rückstrich gequotet.
    public static func execStartValue(for executablePath: String) -> String {
        let needsQuoting = executablePath.contains(" ")
            || executablePath.contains("\"")
            || executablePath.contains("\\")
            || executablePath.contains("'")
        guard needsQuoting else { return executablePath }
        var escaped = ""
        for character in executablePath {
            if character == "\"" || character == "\\" { escaped.append("\\") }
            escaped.append(character)
        }
        return "\"\(escaped)\""
    }
}
